# Generated by Django 4.2.2 on 2023-06-30 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HighSchoolMajor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("family_name", models.CharField(max_length=100)),
                ("national_id", models.CharField(max_length=100)),
                ("courses", models.ManyToManyField(to="product.course")),
                (
                    "high_school_major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.highschoolmajor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="high_school_major",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="product.highschoolmajor",
            ),
        ),
    ]
